FROM ubuntu:24.04
RUN apt-get update 
RUN apt-get install -y python3 python3-pip python3-dev 
RUN apt-get install -y git 
RUN apt-get install -y python3-venv pipx

COPY requirements.txt ./app/
COPY * ./app/
WORKDIR ./app
#RUN apt install pipx && pipx install some-python-application
RUN python3 -m venv /home/ubuntu/venv
ENV PATH="/home/ubuntu/venv/bin:$PATH"
RUN pip3 install -r requirements.txt
#CMD ["python3", "main.py"]

